### ISSUE TITLE
Sitemap broken

### ISSUE THREAD

**Issue by anibalsolon** [WomenInNeuroscience/winrepo-fork-archive#24]
**Describe the bug**
The endpoint for indexers to retrieve the [sitemap](https://developers.google.com/search/docs/advanced/sitemaps/overview) is broken, showing the exception:

```
Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File ".../site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File ".../site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../site-packages/django/contrib/sitemaps/views.py", line 16, in inner
    response = func(request, *args, **kwargs)
  File ".../site-packages/django/contrib/sitemaps/views.py", line 70, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site,
  File ".../site-packages/django/contrib/sitemaps/__init__.py", line 112, in get_urls
    urls = self._urls(page, protocol, domain)
  File ".../site-packages/django/contrib/sitemaps/__init__.py", line 121, in _urls
    loc = "%s://%s%s" % (protocol, domain, self.__get('location', item))
  File ".../site-packages/django/contrib/sitemaps/__init__.py", line 69, in __get
    return attr(obj)
  File ".../site-packages/django/contrib/sitemaps/__init__.py", line 76, in location
    return obj.get_absolute_url()
AttributeError: 'Profile' object has no attribute 'get_absolute_url'
```

**To Reproduce**
Access /sitemap.xml

**Expected behavior**
Render a XML with the site content

**Comment by HugoFara** [comment]
Fixed in #49 .
